version: '3'

services:
  notebook:
    image: nginx:stable-alpine
#    build:
#      context: ./
#      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    container_name: notebook
    volumes:
      - ../../book/.vuepress/dist/:/usr/share/nginx/notebook/
      - ./notebook.conf:/etc/nginx/conf.d/notebook.conf
    environment:
      NOTEBOOK_ENV: prd # no use
    cap_add:
      - SYS_PTRACE
