import { sidebar } from "vuepress-theme-hope";

function buildSimpleNavObj(title: string, icon: string = "markdown-black") {
  return {
    text: title,
    link: title,
    icon: icon,
  }
}

const FOLDER_ICON = "folder";

export default sidebar({
  "/": [],
  "/Java/": [
    {
      text: "踏入山门",
      prefix: "踏入山门/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("Java语言概述"),
        buildSimpleNavObj("理解面向对象"),
        buildSimpleNavObj("标识符、关键字、直接量"),
        buildSimpleNavObj("数据类型"),
        buildSimpleNavObj("包装类"),
        buildSimpleNavObj("运算符"),
        buildSimpleNavObj("Java注释"),
        buildSimpleNavObj("流程控制"),
        buildSimpleNavObj("数组"),
        buildSimpleNavObj("classpath和jar"),
        buildSimpleNavObj("异常"),
        buildSimpleNavObj("注解"),
      ]
    },
    {
      text: "面向对象",
      prefix: "面向对象/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("类与对象"),
        buildSimpleNavObj("类的继承"),
        buildSimpleNavObj("类的组合"),
        buildSimpleNavObj("初始化块"),
        buildSimpleNavObj("多态"),
        buildSimpleNavObj("final关键字"),
        buildSimpleNavObj("包"),
        buildSimpleNavObj("对象与垃圾回收"),
        buildSimpleNavObj("抽象类"),
        buildSimpleNavObj("接口"),
        buildSimpleNavObj("内部类"),
        buildSimpleNavObj("枚举类"),
        buildSimpleNavObj("函数式接口"),
        buildSimpleNavObj("Lambda表达式"),
        buildSimpleNavObj("一些Java常用接口"),
        buildSimpleNavObj("泛型"),
      ]
    },
    {
      text: "类加载机制及反射",
      prefix: "类加载机制及反射/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("类的加载、连接、初始化"),
        buildSimpleNavObj("类加载器"),
        buildSimpleNavObj("反射"),
        buildSimpleNavObj("代理"),
      ]
    },
    {
      text: "基础类库",
      prefix: "基础类库/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("Scanner类"),
        buildSimpleNavObj("Console类"),
        buildSimpleNavObj("System类"),
        buildSimpleNavObj("Runtime类"),
        buildSimpleNavObj("Object类"),
        buildSimpleNavObj("Objects类"),
        buildSimpleNavObj("Math类"),
        buildSimpleNavObj("Random、ThreadLocalRandom类"),
        buildSimpleNavObj("String、StringBuilder、StringBuffer类"),
        buildSimpleNavObj("BigDecimal类"),
        buildSimpleNavObj("Optional类"),
        buildSimpleNavObj("日期与时间"),
        buildSimpleNavObj("正则表达式"),
        buildSimpleNavObj("PropertyEditor类"),
        buildSimpleNavObj("Proxy类"),
      ]
    },
    {
      text: "集合与流",
      prefix: "集合与流/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("Java集合概述"),
        buildSimpleNavObj("List"),
        buildSimpleNavObj("Queue"),
        buildSimpleNavObj("Set"),
        buildSimpleNavObj("Map"),
        buildSimpleNavObj("视图与包装器"),
        buildSimpleNavObj("算法"),
        buildSimpleNavObj("流"),
      ]
    },
    {
      text: "IO",
      prefix: "IO/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("JavaIO概述"),
        buildSimpleNavObj("JavaIO流设计模型"),
        buildSimpleNavObj("JavaIO工作的机制"),
        buildSimpleNavObj("File类"),
        buildSimpleNavObj("RandomAccessFile类"),
        buildSimpleNavObj("NIO"),
        buildSimpleNavObj("IO调优"),
        buildSimpleNavObj("对象序列化"),
        buildSimpleNavObj("读取properties配置文件"),
      ]
    },
    {
      text: "多线程",
      prefix: "多线程/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("多线程概述"),
        buildSimpleNavObj("线程创建及启动"),
        buildSimpleNavObj("线程的生命周期"),
        buildSimpleNavObj("线程属性"),
        buildSimpleNavObj("线程同步"),
        buildSimpleNavObj("线程安全的集合"),
        buildSimpleNavObj("线程池"),
        buildSimpleNavObj("异步计算"),
        buildSimpleNavObj("线程组"),
        buildSimpleNavObj("进程"),
      ]
    },
    {
      text: "网络编程",
      prefix: "网络编程/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("基础知识"),
        buildSimpleNavObj("InetAddress"),
        buildSimpleNavObj("URLDecoder、URLEncoder"),
        buildSimpleNavObj("URL、URLConnection"),
        buildSimpleNavObj("TCP编程"),
        buildSimpleNavObj("UDP编程"),
        buildSimpleNavObj("Proxy、ProxySelector"),
      ]
    },
    {
      text: "图形用户界面",
      prefix: "图形用户界面/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("Applet"),
        buildSimpleNavObj("绘图"),
        buildSimpleNavObj("Swing基础"),
        buildSimpleNavObj("Swing事件"),
        buildSimpleNavObj("Swing组件详解"),
        buildSimpleNavObj("其他Swing特性"),
        buildSimpleNavObj("桌面API"),
      ]
    },
    {
      text: "设计模式",
      prefix: "设计模式/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        {
          text: "创建型模式",
          prefix: "创建型模式/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("工厂模式"),
            buildSimpleNavObj("抽象工厂模式"),
            buildSimpleNavObj("单例模式"),
            buildSimpleNavObj("建造者模式"),
            buildSimpleNavObj("原型模式"),
          ]
        },
        {
          text: "结构型模式",
          prefix: "结构型模式/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("适配器模式"),
            buildSimpleNavObj("装饰器模式"),
            buildSimpleNavObj("代理模式"),
            buildSimpleNavObj("外观模式"),
            buildSimpleNavObj("桥接模式"),
            buildSimpleNavObj("组合模式"),
            buildSimpleNavObj("享元模式"),
          ]
        },
        {
          text: "行为型模式",
          prefix: "行为型模式/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("策略模式"),
            buildSimpleNavObj("模板模式"),
            buildSimpleNavObj("观察者模式"),
            buildSimpleNavObj("迭代器模式"),
            buildSimpleNavObj("责任链模式"),
            buildSimpleNavObj("命令模式"),
            buildSimpleNavObj("备忘录模式"),
            buildSimpleNavObj("状态模式"),
            buildSimpleNavObj("访问者模式"),
            buildSimpleNavObj("中介者模式"),
            buildSimpleNavObj("解释器模式"),
          ]
        },
      ]
    },
    {
      text: "第三方工具",
      prefix: "第三方工具/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("lombok"),
        buildSimpleNavObj("Junit测试"),
        buildSimpleNavObj("Json"),
        {
          text: "Guava",
          prefix: "Guava/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("Cache"),
            buildSimpleNavObj("EventBus"),
          ]
        },
      ]
    },
    {
      text: "Java开发工具",
      prefix: "Java开发工具/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("Maven"),
        buildSimpleNavObj("IDEA"),
      ]
    },
  ],
  "/JavaWeb/": [
    {
      text: "Web后端基础",
      prefix: "Web后端基础/",
      collapsible: true,
      icon: "backend-dev",
      children: [
        buildSimpleNavObj("Web请求过程"),
        buildSimpleNavObj("Tomcat"),
        buildSimpleNavObj("Servlet"),
        buildSimpleNavObj("请求与响应"),
        buildSimpleNavObj("ServletContext"),
        buildSimpleNavObj("会话技术"),
        buildSimpleNavObj("JSP"),
        buildSimpleNavObj("Filter"),
        buildSimpleNavObj("Listener"),
        buildSimpleNavObj("中文编码问题"),
        buildSimpleNavObj("MVC开发模式"),
        buildSimpleNavObj("JDBC简介"),
      ]
    },
    {
      text: "Spring",
      prefix: "Spring/",
      collapsible: true,
      icon: "spring",
      children: [
        buildSimpleNavObj("IoC-上"),
        buildSimpleNavObj("IoC-下"),
        buildSimpleNavObj("配置-XML"),
        buildSimpleNavObj("配置-注解"),
        buildSimpleNavObj("配置-代码"),
        buildSimpleNavObj("AOP-上"),
        buildSimpleNavObj("AOP-下"),
        buildSimpleNavObj("贯通"),
        buildSimpleNavObj("Spring+Junit"),
        buildSimpleNavObj("Spring-JdbcTemplate"),
      ]
    },
    {
      text: "SpringMVC",
      prefix: "SpringMVC/",
      collapsible: true,
      icon: "MVC",
      children: [
        buildSimpleNavObj("SpringMVC简介"),
        buildSimpleNavObj("接收请求与设置响应"),
        buildSimpleNavObj("转换、过滤、拦截、异常"),
        buildSimpleNavObj("SpringMVC的主要注解"),
        buildSimpleNavObj("案例：文件上传"),
      ]
    },
    {
      text: "MyBatis",
      prefix: "MyBatis/",
      collapsible: true,
      icon: "mybatis",
      children: [
        buildSimpleNavObj("持久层技术"),
        buildSimpleNavObj("MyBatis入门"),
        buildSimpleNavObj("MyBatis的API"),
        buildSimpleNavObj("SqlMapConfig.xml"),
        buildSimpleNavObj("XxxMapper.xml"),
        buildSimpleNavObj("MyBatis集成于DAO层"),
        buildSimpleNavObj("动态代理开发"),
        buildSimpleNavObj("MyBatis注解开发"),
        buildSimpleNavObj("MyBatis缓存结构"),
        buildSimpleNavObj("MyBatis逆向工程"),
        buildSimpleNavObj("SSM整合"),
      ]
    },
    {
      text: "SpringBoot",
      prefix: "SpringBoot/",
      collapsible: true,
      icon: "spring-boot",
      children: [
        buildSimpleNavObj("踏入山门"),
        buildSimpleNavObj("SpringBoot配置"),
        buildSimpleNavObj("集成其他框架"),
        buildSimpleNavObj("远程调试"),
      ]
    },
    {
      text: "SpringCloud",
      prefix: "SpringCloud/",
      collapsible: true,
      icon: "spring-cloud",
      children: [
        buildSimpleNavObj("RestTemplate"),
        buildSimpleNavObj("OpenFeign"),
        buildSimpleNavObj("Config"),
        buildSimpleNavObj("Zookeeper"),
        buildSimpleNavObj("Gateway"),
        buildSimpleNavObj("Stream"),
        buildSimpleNavObj("RabbitMQ", "rabbitmq"),
        {
          text: "Netflix",
          prefix: "Netflix/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("Eureka"),
            buildSimpleNavObj("Ribbon"),
            buildSimpleNavObj("Zuul"),
          ]
        },
        {
          text: "Alibaba",
          prefix: "Alibaba/",
          collapsible: true,
          icon: FOLDER_ICON,
          children: [
            buildSimpleNavObj("Nacos"),
          ]
        },
      ]
    },
    {
      text: "SpringData",
      prefix: "SpringData/",
      collapsible: true,
      icon: "spring-data",
      children: [
        buildSimpleNavObj("JPA基础"),
        buildSimpleNavObj("SpringData-JPA"),
        buildSimpleNavObj("SpringData-MongoDB"),
      ]
    },
    {
      text: "SpringSecurity",
      prefix: "SpringSecurity/",
      collapsible: true,
      icon: "security-1",
      children: [
        buildSimpleNavObj("踏入山门"),
        buildSimpleNavObj("认证"),
        buildSimpleNavObj("授权"),
        buildSimpleNavObj("自定义异常处理"),
      ]
    },
    {
      text: "Web安全",
      prefix: "Web安全/",
      collapsible: true,
      icon: "security",
      children: [
        buildSimpleNavObj("认证与授权"),
        buildSimpleNavObj("JWT"),
        buildSimpleNavObj("OAuth2.0"),
        buildSimpleNavObj("数据脱敏"),
      ]
    },
    {
      text: "其他",
      prefix: "其他/",
      collapsible: true,
      icon: "other-tech",
      children: [
        buildSimpleNavObj("YAML概述", "yaml"),
        buildSimpleNavObj("Swagger", "swagger"),
        buildSimpleNavObj("前后端交互", "interactive"),
        buildSimpleNavObj("RESTful", "restful"),
      ]
    },
  ],
  "/JavaScript/": [
    buildSimpleNavObj("web概念概述"),
    buildSimpleNavObj("HTML&CSS"),
    buildSimpleNavObj("JavaScript"),
    buildSimpleNavObj("XML"),
    {
      text: "Vue",
      prefix: "Vue/",
      collapsible: true,
      icon: "vuejs",
      children: [
        buildSimpleNavObj("1.Vue.js介绍"),
        buildSimpleNavObj("2.Vue对象"),
        buildSimpleNavObj("3.Vue模板语法"),
        buildSimpleNavObj("4.组件"),
        buildSimpleNavObj("5.混入"),
        buildSimpleNavObj("6.插件"),
        buildSimpleNavObj("7.过滤器"),
        buildSimpleNavObj("8.状态管理"),
        buildSimpleNavObj("9.路由"),
      ]
    },
  ],
  "/Python/": [
    {
      text: "踏入山门",
      prefix: "踏入山门/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("前言"),
        buildSimpleNavObj("内置操作"),
        buildSimpleNavObj("运算"),
        buildSimpleNavObj("字符串"),
        buildSimpleNavObj("数字"),
        buildSimpleNavObj("容器类"),
        buildSimpleNavObj("程序控制语句"),
        buildSimpleNavObj("函数"),
        buildSimpleNavObj("作用域"),
        buildSimpleNavObj("类"),
        buildSimpleNavObj("文件"),
        buildSimpleNavObj("异常"),
        buildSimpleNavObj("模块与包"),
        buildSimpleNavObj("迭代器-生成器-装饰器-描述器"),
        buildSimpleNavObj("元编程"),
        buildSimpleNavObj("并发编程"),
      ]
    },
    {
      text: "标准库",
      prefix: "标准库/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("os"),
        buildSimpleNavObj("collections"),
        buildSimpleNavObj("heapq"),
        buildSimpleNavObj("operator"),
        buildSimpleNavObj("itertools"),
        buildSimpleNavObj("weakref"),
        buildSimpleNavObj("functools"),
        buildSimpleNavObj("shutil"),
        buildSimpleNavObj("regex"),
      ]
    },
    {
      text: "numpy",
      prefix: "numpy/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("numpy简介"),
        buildSimpleNavObj("数组操作"),
        buildSimpleNavObj("结构化数组"),
        buildSimpleNavObj("其他"),
      ]
    },
    {
      text: "pandas",
      prefix: "pandas/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("概述"),
        buildSimpleNavObj("数据操作"),
        buildSimpleNavObj("缺失值处理"),
        buildSimpleNavObj("eval与query"),
        buildSimpleNavObj("IO操作"),
      ]
    },
    {
      text: "scipy",
      prefix: "scipy/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("概述"),
      ]
    },
    {
      text: "matplotlib",
      prefix: "matplotlib/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("基础介绍"),
        buildSimpleNavObj("图件配置"),
        buildSimpleNavObj("各种图件"),
      ]
    },
    {
      text: "mayavi",
      prefix: "mayavi/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("mayavi综述"),
        buildSimpleNavObj("mlab"),
        buildSimpleNavObj("远程使用mayavi"),
      ]
    },
    {
      text: "scikit-image",
      prefix: "scikit-image/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("通性概念"),
        buildSimpleNavObj("图像算法"),
      ]
    },
    {
      text: "PyTorch",
      prefix: "PyTorch/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("torch"),
        buildSimpleNavObj("Tensor"),
        buildSimpleNavObj("torch.nn"),
        buildSimpleNavObj("torch.optim"),
        buildSimpleNavObj("模型保存与加载"),
        buildSimpleNavObj("validation"),
      ]
    },
  ],
  "/数学/": [
    {
      text: "线性代数",
      prefix: "线性代数/",
      collapsible: true,
      icon: FOLDER_ICON,
      children: [
        buildSimpleNavObj("矩阵"),
      ]
    },
  ],
  "/DSA/": [
    {
      text: "LeetCode",
      prefix: "LeetCode/",
      collapsible: true,
      icon: "leetcode",
      children: [
        buildSimpleNavObj("001. Two Sum"),
        buildSimpleNavObj("002. Add Two Numbers"),
        buildSimpleNavObj("003. Longest Substring Without Repeating Characters"),
        buildSimpleNavObj("005. Longest Palindromic Substring"),
        buildSimpleNavObj("006. ZigZag Conversion"),
        buildSimpleNavObj("007. Reverse Interger"),
        buildSimpleNavObj("008. String to Integer (atoi),"),
        buildSimpleNavObj("009. Palindrome Number"),
        buildSimpleNavObj("011. Container With Most Water"),
        buildSimpleNavObj("012. Integer to Roman"),
        buildSimpleNavObj("013. Roman to Integer"),
        buildSimpleNavObj("014. Longest Common Prefix"),
        buildSimpleNavObj("015. 3Sum"),
        buildSimpleNavObj("016. 3Sum Closest"),
        buildSimpleNavObj("017. Letter Combinations of a Phone Number"),
        buildSimpleNavObj("018. 4Sum"),
        buildSimpleNavObj("019. Remove Nth Node From End of List"),
        buildSimpleNavObj("020. Valid Parenttheses"),
        buildSimpleNavObj("021. Merge Two Sorted Lists"),
        buildSimpleNavObj("022. Generate Parentheses"),
        buildSimpleNavObj("024. Swap Nodes in Pairs"),
        buildSimpleNavObj("026. Remove Duplicates from Sorted Array"),
        buildSimpleNavObj("027. Remove Element"),
        buildSimpleNavObj("028. Implement strStr(),"),
        buildSimpleNavObj("029. Divide Two Integers"),
        buildSimpleNavObj("031. Next Permutation"),
        buildSimpleNavObj("033. Search in Rotated Sorted Array"),
        buildSimpleNavObj("034. Find First and Last Position of Element in Sorted Array"),
        buildSimpleNavObj("035. Search Insert Position"),
        buildSimpleNavObj("036. Valid Sudoku"),
        buildSimpleNavObj("038. Count and Say"),
        buildSimpleNavObj("039. Combination Sum"),
        buildSimpleNavObj("040. Combination Sum II"),
        buildSimpleNavObj("043. Multiply Strings"),
        buildSimpleNavObj("046. Permutations"),
        buildSimpleNavObj("047. Permutations II"),
        buildSimpleNavObj("048. Rotate Image"),
        buildSimpleNavObj("049. Group Anagrams"),
        buildSimpleNavObj("050. Pow(x, n),"),
        buildSimpleNavObj("053. Maximum Subarray"),
        buildSimpleNavObj("054. Spiral Matrix"),
        buildSimpleNavObj("055. Jump Game"),
        buildSimpleNavObj("056. Merge Intervals"),
        buildSimpleNavObj("058. Length of Last Word"),
        buildSimpleNavObj("059. Spiral Matrix II"),
        buildSimpleNavObj("060. Permutation Sequence"),
        buildSimpleNavObj("061. Rotate List"),
        buildSimpleNavObj("062. Unique Paths"),
        buildSimpleNavObj("063. Unique Paths II"),
        buildSimpleNavObj("064. Minimum Path Sum"),
        buildSimpleNavObj("066. Plus One"),
        buildSimpleNavObj("067. Add Binary"),
        buildSimpleNavObj("069. Sqrt(x),"),
        buildSimpleNavObj("070. Climbing Stairs"),
        buildSimpleNavObj("071. Simplify Path"),
        buildSimpleNavObj("073. Set Matrix Zeroes"),
        buildSimpleNavObj("074. Search a 2D Matrix"),
        buildSimpleNavObj("075. Sort Colors"),
        buildSimpleNavObj("077. Combinations"),
        buildSimpleNavObj("078. Subsets"),
        buildSimpleNavObj("079. Word Search"),
        buildSimpleNavObj("080. Remove Duplicates from Sorted Array II"),
        buildSimpleNavObj("081. Search in Rotated Sorted Array II"),
        buildSimpleNavObj("083. Remove Duplicates from Sorted List"),
        buildSimpleNavObj("086. Partition List"),
        buildSimpleNavObj("088. Merge Sorted Array"),
        buildSimpleNavObj("089. Gray Code"),
        buildSimpleNavObj("090. Subsets II"),
        buildSimpleNavObj("091. Decode Ways"),
        buildSimpleNavObj("100. Same Tree"),
        buildSimpleNavObj("101. Symmetric Tree"),
        buildSimpleNavObj("104. Maximum Depth of Binary Tree"),
        buildSimpleNavObj("107. Binary Tree Level Order Traversal II"),
        buildSimpleNavObj("108. Convert Sorted Array to Binary Search Tree"),
        buildSimpleNavObj("110. Balanced Binary Tree"),
        buildSimpleNavObj("111. Minimum Depth of Binary Tree"),
        buildSimpleNavObj("112. Path Sum"),
        buildSimpleNavObj("118. Pascal's Triangle"),
        buildSimpleNavObj("119. Pascal's Triangle II"),
        buildSimpleNavObj("121. Best Time to Buy and Sell Stock"),
        buildSimpleNavObj("122. Best Time to Buy and Sell Stock II"),
        buildSimpleNavObj("125. Valid Palindrome"),
        buildSimpleNavObj("131. Palindrome Partitioning"),
        buildSimpleNavObj("136. Single Number"),
        buildSimpleNavObj("141. Linked List Cycle"),
        buildSimpleNavObj("155. Min Stack"),
        buildSimpleNavObj("160. Intersection of Two Linked Lists"),
        buildSimpleNavObj("167. Two Sum II - Input array is sorted"),
        buildSimpleNavObj("168. Excel Sheet Column Title"),
        buildSimpleNavObj("169. Majority Element"),
        buildSimpleNavObj("171. Excel Sheet Column Number"),
        buildSimpleNavObj("172. Factorial Trailing Zeroes"),
        buildSimpleNavObj("189. Rotate Array"),
        buildSimpleNavObj("190. Reverse Bits"),
        buildSimpleNavObj("191. Number of 1 Bits"),
        buildSimpleNavObj("198. House Robber"),
        buildSimpleNavObj("202. Happy Number"),
        buildSimpleNavObj("203. Remove Linked List Elements"),
        buildSimpleNavObj("216. Combination Sum III"),
      ]
    },
    {
      text: "剑指offer",
      prefix: "剑指offer/",
      collapsible: true,
      icon: "offer-1",
      // children: "structure"
      children: [
        buildSimpleNavObj("01.Search_in_2D_Array"),
        buildSimpleNavObj("02.Replace_the_Blank_Space"),
        buildSimpleNavObj("03.Print_Linked_List"),
        buildSimpleNavObj("04.Reconstruct_Binary_Tree"),
        buildSimpleNavObj("05.Implement_A_Queue_Using_Two_Stacks"),
        buildSimpleNavObj("06.Minimum_Number_of_Rotation_Array"),
        buildSimpleNavObj("07.Fibonacci_Sequence"),
        buildSimpleNavObj("08.Jumping_Steps"),
        buildSimpleNavObj("09.Jumping_Steps_II"),
        buildSimpleNavObj("10.Rectangle_Covering"),
        buildSimpleNavObj("11.Number_of_1_in_Binary_Representation"),
        buildSimpleNavObj("12.Integer_Power_of_a_Value"),
        buildSimpleNavObj("13.Make_the_Odd_Number_Precedes_the_Even"),
        buildSimpleNavObj("14.The_Last_K_Node_in_the_List"),
        buildSimpleNavObj("15.Reverse_Linked_List"),
        buildSimpleNavObj("16.Merge_Two_Sorted_List"),
        buildSimpleNavObj("17.Substructure_of_a_Tree"),
        buildSimpleNavObj("18.Mirror_of_Binary_Tree"),
        buildSimpleNavObj("19.Print_Matrix_Clockwise"),
        buildSimpleNavObj("20.Implement_Stack_with_Min_Function"),
        buildSimpleNavObj("21.Push_And_Pop_Sequence_of_Stack"),
        buildSimpleNavObj("22.Print_Binary_Tree_From_Up_To_Down"),
        buildSimpleNavObj("23.Verify_Post_Order_Traverse_Of_BST"),
        buildSimpleNavObj("24.Path_That_Sums_to_a_Certain_Value_in_a_Binary_Tree"),
        buildSimpleNavObj("25.Copy_a_Complicated_List"),
        buildSimpleNavObj("26.Conver_BST_to_Sorted_Doubly_Linked_List"),
        buildSimpleNavObj("27.Permutations_of_String"),
        buildSimpleNavObj("28.Find_a_Number_That_Occurs_More_Than_Half_Times_in_an_Array"),
        buildSimpleNavObj("29.Get_Least_Numbers_of_Array"),
        buildSimpleNavObj("30.Find_Greatest_Sum_of_Subarray"),
        buildSimpleNavObj("31.Number_of_1_Between_1_And_N"),
        buildSimpleNavObj("32.Permute_an_Array_into_the_Smallest_Number"),
        buildSimpleNavObj("33.N-th_Ugly_Number"),
        buildSimpleNavObj("34.First_Not_Repeating_Char"),
        buildSimpleNavObj("35.Inverse_Pairs_of_Array"),
        buildSimpleNavObj("36.First_Common_Node_of_Two_Lists"),
        buildSimpleNavObj("37.Get_Number_of_Value_K_in_Sorted_Array"),
        buildSimpleNavObj("38.Depth_of_Binary_Tree"),
        buildSimpleNavObj("39.Whether_a_Binary_Tree_Is_Balanced"),
        buildSimpleNavObj("40.Find_Only_Two_Numbers_That_Appear_Once_in_Array"),
        buildSimpleNavObj("41.All_Continuous_Sequences_Sum_to_N"),
        buildSimpleNavObj("42.Find_Two_Numbers_Sum_to_S_in_Sorted_Array"),
        buildSimpleNavObj("43.Left_Rotate_String"),
        buildSimpleNavObj("44.Reverse_Sentence"),
        buildSimpleNavObj("45.Playing_Card_Shunzi"),
        buildSimpleNavObj("46.Last_Remaining_in_Circle"),
        buildSimpleNavObj("47.Solve_1+2+3+...+n"),
        buildSimpleNavObj("48.Add_Numbers_without_Addition_Subtraction_Multiplication_And_Division"),
        buildSimpleNavObj("49.String_to_Integer"),
        buildSimpleNavObj("50.Duplicate_Numbers_in_Array"),
        buildSimpleNavObj("51.Build_Product_Array"),
        buildSimpleNavObj("52.Regular_Expression_Matching"),
        buildSimpleNavObj("53.Whether_a_String_Is_Numeric"),
        buildSimpleNavObj("54.First_Non_Repeating_Character_in_Character_Stream"),
        buildSimpleNavObj("55.Entry_Node_of_Loop_in_List"),
        buildSimpleNavObj("56.Delete_Duplications_in_Sorted_List"),
        buildSimpleNavObj("57.Next_Node_in_Binary_Tree"),
        buildSimpleNavObj("58.Symmetrical_Binary_Tree"),
        buildSimpleNavObj("59.Print_Binary_Tree_in_Zigzag_Order"),
        buildSimpleNavObj("60.Print_Binary_Tree_into_Multiple_lines"),
        buildSimpleNavObj("61.Serialize_And_Deserialize_Binary_Tree"),
        buildSimpleNavObj("62.K-th_Node_of_BST"),
        buildSimpleNavObj("63.Median_of_Data_Flow"),
        buildSimpleNavObj("64.Maximum_in_Sliding_Window"),
        buildSimpleNavObj("65.Path_in_Matrix"),
        buildSimpleNavObj("66.Range_of_Motion_of_Robot"),
        buildSimpleNavObj("67.Cut_Rope"),
      ]
    },
    {
      text: "interview",
      prefix: "interview/",
      collapsible: true,
      icon: "interview",
      children: [
        buildSimpleNavObj("0-1背包问题"),
        buildSimpleNavObj("最大正方形"),
      ]
    },
    {
      text: "trick",
      prefix: "trick/",
      collapsible: true,
      icon: "bulb",
      children: [
        buildSimpleNavObj("排序"),
        buildSimpleNavObj("二叉树"),
        buildSimpleNavObj("二叉搜索树"),
        buildSimpleNavObj("图"),
      ]
    },
  ],
  "/数据库/": [
    buildSimpleNavObj("数据库概论"),
    {
      text: "MySQL",
      prefix: "MySQL/",
      collapsible: true,
      icon: "mysql",
      children: [
        buildSimpleNavObj("安装使用及维护"),
        buildSimpleNavObj("schema"),
        buildSimpleNavObj("SQL语法"),
        buildSimpleNavObj("SQL语言"),
        buildSimpleNavObj("索引"),
        buildSimpleNavObj("事务"),
        buildSimpleNavObj("全文本搜索"),
        buildSimpleNavObj("视图"),
        buildSimpleNavObj("存储过程、游标、触发器"),
        buildSimpleNavObj("MySQL调优"),
      ]
    },
    {
      text: "mongoDB",
      prefix: "mongoDB/",
      collapsible: true,
      icon: "mongodb",
      children: [
        buildSimpleNavObj("概念解析"),
      ]
    },
    {
      text: "Redis",
      prefix: "Redis/",
      collapsible: true,
      icon: "redis",
      children: [
        buildSimpleNavObj("踏入山门"),
        buildSimpleNavObj("数据类型"),
        buildSimpleNavObj("Redis命令"),
        buildSimpleNavObj("配置文件"),
        buildSimpleNavObj("发布-订阅"),
        buildSimpleNavObj("Stream消息队列"),
        buildSimpleNavObj("Redis事务"),
        buildSimpleNavObj("Redis持久化"),
        buildSimpleNavObj("Redis集群与分布式锁"),
        buildSimpleNavObj("Redis缓存问题"),
        buildSimpleNavObj("Jedis"),
      ]
    },
    {
      text: "Elasticsearch",
      prefix: "Elasticsearch/",
      collapsible: true,
      icon: "elasticsearch",
      children: [
        buildSimpleNavObj("概述"),
        buildSimpleNavObj("DSL"),
        buildSimpleNavObj("RestAPI"),
        buildSimpleNavObj("自动补全"),
        buildSimpleNavObj("数据同步"),
        buildSimpleNavObj("ES集群"),
      ]
    },
  ],
  "/Linux/": [
    buildSimpleNavObj("总览"),
    buildSimpleNavObj("文件操作"),
    buildSimpleNavObj("进程管理"),
    buildSimpleNavObj("用户管理"),
    buildSimpleNavObj("文件权限"),
    buildSimpleNavObj("磁盘管理"),
    buildSimpleNavObj("软件管理"),
    buildSimpleNavObj("shell脚本"),
    buildSimpleNavObj("网络操作"),
    buildSimpleNavObj("乌合之令"),
    buildSimpleNavObj("WSL"),
  ],
  "/杂技/": [
    {
      text: "计算机组成原理",
      prefix: "计算机组成原理/",
      // collapsible: true,
      icon: "CPU",
      children: [
      ]
    },
    {
      text: "计算机网络",
      prefix: "计算机网络/",
      collapsible: true,
      icon: "computer-network",
      children: [
        buildSimpleNavObj("概要"),
        buildSimpleNavObj("计网体系结构"),
        buildSimpleNavObj("HTTP协议"),
        buildSimpleNavObj("WebSocket"),
      ]
    },
    {
      text: "操作系统",
      prefix: "操作系统/",
      // collapsible: true,
      icon: "operating-system",
      children: [
      ]
    },
    {
      text: "C++",
      prefix: "C++/",
      // collapsible: true,
      icon: "cpp",
      children: [
      ]
    },
    {
      text: "Git",
      prefix: "Git/",
      collapsible: true,
      icon: "git",
      children: [
        buildSimpleNavObj("一、Git起步"),
        buildSimpleNavObj("二、版本控制"),
        buildSimpleNavObj("三、远程仓库"),
        buildSimpleNavObj("四、标签管理"),
        buildSimpleNavObj("五、Git分支"),
      ]
    },
    buildSimpleNavObj("Docker", "docker"),
    buildSimpleNavObj("Nginx", "nginx"),
    {
      text: "CV",
      prefix: "CV/",
      collapsible: true,
      icon: "computer-vision-simple",
      children: [
        buildSimpleNavObj("基础概念"),
        buildSimpleNavObj("空间域处理"),
        buildSimpleNavObj("频率域滤波"),
        buildSimpleNavObj("图像复原与重建"),
        buildSimpleNavObj("形态学图像处理"),
        buildSimpleNavObj("彩色图像处理"),
        buildSimpleNavObj("小波变换"),
      ]
    },
  ],
});
