name: Build the notebook and deploy to github pages

on:
  push:
    branches:
      - feature/goto-webpack
  pull_request:
    branches:
      - feature/goto-webpack

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x # latest
          # cache: 'npm'

      - name: Go to _app/ directory, install Dependencies, build the project
        run: |
          yarn install
          yarn build
        working-directory: ./_app/
  deploy:
    needs: build # 需 build 任务完成之后才可以执行 deploy 任务
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to the github pages
        uses: peaceiris/actions-gh-pages@v3 # 使用第三方 Action 把构建完成的 Artifact 部署到指定分支
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # default
          publish_dir: ./_app/dist  # default: public
