name: Build the notebook and deploy to github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x # latest
          # cache: 'npm'

      - name: Go to _app/ directory, install Dependencies, build the project
        run: |
          yarn install
          yarn build
        working-directory: ./_app/

      - name: Deploy to the github pages
        uses: peaceiris/actions-gh-pages@v3 # 使用第三方 Action 把构建完成的 Artifact 部署到指定分支
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # default
          publish_dir: ./_app/dist  # default: public
